### ISSUE TITLE
[platform] VSCode extension

### ISSUE THREAD

**Issue by sassdawe** [merill/InclusivenessAnalyzer#7]
Greetings,

Would it be possible to turn this into a VSCode extension as well?

Thanks!

**Comment by merill** [comment]
vscode has a couple of great extensions with similar capability. Try them out.

- [Woke](https://marketplace.visualstudio.com/items?itemName=get-woke.vscode-woke)
- [Inclusive Lint](https://marketplace.visualstudio.com/items?itemName=inclusivelint.inclusivelint-vscode)
